version: '3'
services:
  nodejs:
    build: .
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    volumes:
    - ./:/var/www/html
    environment:
      - NODE_ENV=development
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=your_rabbitmq_user
      - RABBITMQ_DEFAULT_PASS=your_rabbitmq_password

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  postgres_data: